name: Deploy (GCP Cloud Run + Cloud SQL)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write   # IMPORTANT√çSIMO para WIF

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: ${{ secrets.GCP_REGION }}
      IMAGE: ${{ secrets.GCP_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/accenture-repo/accenture-api:latest

    steps:
      - uses: actions/checkout@v4

      - name: Auth to GCP (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}
          service_account: ${{ secrets.GCP_SA_EMAIL }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Terraform Init
        working-directory: iac/terraform-gcp
        run: terraform init

      - name: Terraform Apply (create infra baseline)
        working-directory: iac/terraform-gcp
        run: |
          terraform apply -auto-approve \
            -var="project_id=$PROJECT_ID" \
            -var="region=$REGION" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="image=$IMAGE"

      - name: Configure Docker auth
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build & Push Docker image
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Terraform Apply (deploy latest image)
        working-directory: iac/terraform-gcp
        run: |
          terraform apply -auto-approve \
            -var="project_id=$PROJECT_ID" \
            -var="region=$REGION" \
            -var="db_password=${{ secrets.DB_PASSWORD }}" \
            -var="image=$IMAGE"
